# Generated by Django 3.2.4 on 2021-06-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerDetailsApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='lat',
            field=models.TextField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='lon',
            field=models.TextField(default='0', null=True),
        ),
    ]
